Transaction page
offsetFrontend/offset-go-admin-fe pull request #4
Opened 2024-03-06 07:55 UTC by niteshn1

2024-03-08 06:10 UTC, niteshn1 commented
![Screenshot 2024-03-08 113913](https://github.com/offsetFrontend/offset-go-admin-fe/assets/117146760/df659e50-92f3-4d52-ab9d-718550fa2c52)

2024-03-08 11:03 UTC, souravmsi commented on src/pages/Transactions.jsx
1. remove nested component (Status component). Define this component outside.
2. take a pull from master and add search box component

2024-03-08 11:06 UTC, souravmsi requested changes
check comments!

2024-03-11 06:45 UTC, souravmsi approved these changes
Approved!!

2024-03-11 06:45 UTC, merged